version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: processvenue-postgres
    environment:
      POSTGRES_DB: processvenue
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d processvenue"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: processvenue-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: processvenue-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:password123@postgres:5432/processvenue
      REDIS_URL: redis://redis:6379
      PORT: 3000
      API_BASE_URL: http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    command: npm run dev

volumes:
  postgres_data:
  redis_data:
